In [2]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings('ignore')

sns.set_style('whitegrid')
sns.set_palette('Set2')
sns.set_context('notebook', font_scale=1.5, rc={"lines.linewidth": 2.5})
sns.set_style('ticks')

In [3]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "train.csv"

df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "iabhishekofficial/mobile-price-classification",
    file_path
)

In [4]:
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [5]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='str')

In [6]:
df.shape

(2000, 21)

In [7]:
df['price_range'].value_counts()

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.3 KB

In [9]:
df.describe()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
count,2000.000000,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1238.518500,0.4950,1.522250,0.509500,4.309500,0.521500,32.046500,0.501750,140.249000,4.520500,...,645.108000,1251.515500,2124.213000,12.306500,5.767000,11.011000,0.761500,0.503000,0.507000,1.500000
std,439.418206,0.5001,0.816004,0.500035,4.341444,0.499662,18.145715,0.288416,35.399655,2.287837,...,443.780811,432.199447,1084.732044,4.213245,4.356398,5.463955,0.426273,0.500116,0.500076,1.118314
min,501.000000,0.0000,0.500000,0.000000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,...,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,851.750000,0.0000,0.700000,0.000000,1.000000,0.000000,16.000000,0.200000,109.000000,3.000000,...,282.750000,874.750000,1207.500000,9.000000,2.000000,6.000000,1.000000,0.000000,0.000000,0.750000
50%,1226.000000,0.0000,1.500000,1.000000,3.000000,1.000000,32.000000,0.500000,141.000000,4.000000,...,564.000000,1247.000000,2146.500000,12.000000,5.000000,11.000000,1.000000,1.000000,1.000000,1.500000
75%,1615.250000,1.0000,2.200000,1.000000,7.000000,1.000000,48.000000,0.800000,170.000000,7.000000,...,947.250000,1633.000000,3064.500000,16.000000,9.000000,16.000000,1.000000,1.000000,1.000000,2.250000
max,1998.000000,1.0000,3.000000,1.000000,19.000000,1.000000,64.000000,1.000000,200.000000,8.000000,...,1960.000000,1998.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1.000000,1.000000,3.000000

In [10]:
from sklearn.model_selection import train_test_split

X = df.drop("price_range", axis=1)
y = df["price_range"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [11]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1600, 20), (400, 20), (1600,), (400,))

In [12]:
X_train

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
469,1845,1,0.5,1,10,0,61,0.3,96,1,12,292,695,1731,9,5,6,0,0,0
565,1271,1,0.5,0,12,0,32,0.1,113,7,15,1350,1949,445,15,14,14,0,0,1
396,788,0,2.5,1,4,1,57,0.9,91,8,12,42,1161,3969,12,8,6,1,1,1
452,1406,0,0.5,1,2,1,34,0.8,98,3,5,1017,1366,3915,9,8,2,1,0,1
325,920,0,2.1,1,5,0,25,0.4,115,7,14,209,1078,785,10,7,5,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1170,1100,1,1.6,0,12,0,15,0.1,112,8,14,919,1344,757,12,2,16,1,1,1
100,1883,1,0.5,0,3,1,10,0.3,146,6,13,836,1739,2600,16,8,20,1,0,0
63,1720,0,2.0,0,15,1,55,0.5,168,2,18,753,1353,2148,14,2,5,1,1,1
180,703,1,2.7,0,12,1,30,0.3,113,1,20,218,1065,1472,14,7,7,1,0,0
876,1064,0,2.9,1,1,1,34,0.2,184,6,13,1175,1569,654,16,13,6,1,0,0

In [13]:
from sklearn.svm import SVC

In [14]:
base_model = SVC(random_state=42)
base_model

SVC(random_state=42)

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [16]:
from sklearn.model_selection import cross_val_score

In [17]:
scores = cross_val_score(base_model, X_train, y_train, cv=5, scoring='accuracy')
print(scores.mean())
scores

0.859375

array([0.853125, 0.871875, 0.840625, 0.85    , 0.88125 ])

In [18]:
from sklearn.model_selection import RandomizedSearchCV

param_dist = {

    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto'],
    'class_weight': [None, 'balanced'],
    'coef0': [0.0, 0.1, 0.5, 1.0],
    'probability': [True, False]

}

searcher = RandomizedSearchCV(

    estimator=base_model,
    param_distributions=param_dist,
    n_iter=20,
    scoring='accuracy',
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=2
)

In [19]:
searcher.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=rbf, probability=False; total time=   0.3s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=rbf, probability=False; total time=   0.5s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=rbf, probability=False; total time=   0.6s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=rbf, probability=False; total time=   0.7s
[CV] END C=1, class_weight=balanced, coef0=0.1, gamma=scale, kernel=linear, probability=False; total time=   0.1s
[CV] END C=1, class_weight=balanced, coef0=0.1, gamma=scale, kernel=linear, probability=False; total time=   0.1s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=rbf, probability=False; total time=   0.4s
[CV] END C=1, class_weight=balanced, coef0=0.1, gamma=scale, kernel=linear, probability=False; total time=   0.1s
[CV] END C=1, class_weight=balanced, coef0=0.1, gamma=scale, kernel=linear, probability=False; total time=   0.2s
[CV] END C=1, class_weight=balanced, coef0=0.1, gamma=scale, kernel=linear, probability=False; total time=   0.2s
[CV] END C=10, class_weight=balanced, coef0=0.1, gamma=scale, kernel=poly, probability=True; total time=   1.1s
[CV] END C=10, class_weight=balanced, coef0=0.1, gamma=scale, kernel=poly, probability=True; total time=   1.4s
[CV] END C=10, class_weight=balanced, coef0=0.1, gamma=scale, kernel=poly, probability=True; total time=   1.9s
[CV] END C=10, class_weight=balanced, coef0=0.1, gamma=scale, kernel=poly, probability=True; total time=   2.1s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=linear, probability=True; total time=   0.8s
[CV] END C=10, class_weight=balanced, coef0=0.1, gamma=scale, kernel=poly, probability=True; total time=   1.4s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=linear, probability=True; total time=   0.7s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=linear, probability=True; total time=   0.4s
[CV] END C=1, class_weight=balanced, coef0=1.0, gamma=scale, kernel=linear, probability=False; total time=   0.1s
[CV] END C=1, class_weight=balanced, coef0=1.0, gamma=scale, kernel=linear, probability=False; total time=   0.1s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=linear, probability=True; total time=   0.5s
[CV] END C=1, class_weight=balanced, coef0=1.0, gamma=scale, kernel=linear, probability=False; total time=   0.2s
[CV] END C=1, class_weight=balanced, coef0=1.0, gamma=scale, kernel=linear, probability=False; total time=   0.2s
[CV] END C=1, class_weight=balanced, coef0=1.0, gamma=scale, kernel=linear, probability=False; total time=   0.1s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=linear, probability=True; total time=   0.6s
[CV] END C=0.1, class_weight=None, coef0=0.0, gamma=auto, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=0.1, class_weight=None, coef0=0.0, gamma=auto, kernel=rbf, probability=False; total time=   0.5s
[CV] END C=0.1, class_weight=None, coef0=0.0, gamma=auto, kernel=rbf, probability=False; total time=   0.6s
[CV] END C=0.1, class_weight=None, coef0=0.0, gamma=auto, kernel=rbf, probability=False; total time=   0.3s
[CV] END C=0.1, class_weight=None, coef0=0.0, gamma=auto, kernel=rbf, probability=False; total time=   0.8s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=poly, probability=True; total time=   0.5s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=poly, probability=True; total time=   0.5s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=poly, probability=True; total time=   1.5s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=poly, probability=True; total time=   1.5s
[CV] END C=0.1, class_weight=None, coef0=1.0, gamma=auto, kernel=poly, probability=True; total time=   1.5s
[CV] END C=1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=poly, probability=True; total time=   0.8s
[CV] END C=1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=poly, probability=True; total time=   1.1s
[CV] END C=1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=poly, probability=True; total time=   0.9s
[CV] END C=0.1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=poly, probability=False; total time=   0.4s
[CV] END C=0.1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=poly, probability=False; total time=   0.2s
[CV] END C=1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=poly, probability=True; total time=   0.9s
[CV] END C=0.1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=poly, probability=False; total time=   0.1s
[CV] END C=0.1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=poly, probability=False; total time=   0.2s
[CV] END C=0.1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=poly, probability=False; total time=   0.4s
[CV] END C=10, class_weight=None, coef0=0.0, gamma=scale, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=poly, probability=True; total time=   1.9s
[CV] END C=10, class_weight=None, coef0=0.0, gamma=scale, kernel=rbf, probability=False; total time=   0.3s
[CV] END C=10, class_weight=None, coef0=0.0, gamma=scale, kernel=rbf, probability=False; total time=   0.3s
[CV] END C=10, class_weight=None, coef0=0.0, gamma=scale, kernel=rbf, probability=False; total time=   0.5s
[CV] END C=10, class_weight=None, coef0=0.0, gamma=scale, kernel=rbf, probability=False; total time=   0.7s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=auto, kernel=linear, probability=True; total time=   0.9s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=auto, kernel=linear, probability=True; total time=   0.9s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=auto, kernel=linear, probability=True; total time=   1.6s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=auto, kernel=linear, probability=True; total time=   1.1s
[CV] END C=0.1, class_weight=None, coef0=0.5, gamma=auto, kernel=rbf, probability=False; total time=   0.4s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=auto, kernel=linear, probability=True; total time=   0.8s
[CV] END C=0.1, class_weight=None, coef0=0.5, gamma=auto, kernel=rbf, probability=False; total time=   0.4s
[CV] END C=0.1, class_weight=None, coef0=0.5, gamma=auto, kernel=rbf, probability=False; total time=   0.5s
[CV] END C=0.1, class_weight=None, coef0=0.5, gamma=auto, kernel=rbf, probability=False; total time=   0.5s
[CV] END C=0.1, class_weight=None, coef0=0.5, gamma=auto, kernel=rbf, probability=False; total time=   0.6s
[CV] END C=1, class_weight=None, coef0=0.1, gamma=auto, kernel=rbf, probability=True; total time=   0.7s
[CV] END C=1, class_weight=None, coef0=0.1, gamma=auto, kernel=rbf, probability=True; total time=   1.2s
[CV] END C=1, class_weight=None, coef0=0.1, gamma=auto, kernel=rbf, probability=True; total time=   0.8s
[CV] END C=10, class_weight=balanced, coef0=1.0, gamma=scale, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=10, class_weight=balanced, coef0=1.0, gamma=scale, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=10, class_weight=balanced, coef0=1.0, gamma=scale, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=1, class_weight=None, coef0=0.1, gamma=auto, kernel=rbf, probability=True; total time=   1.4s
[CV] END C=10, class_weight=balanced, coef0=1.0, gamma=scale, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=10, class_weight=balanced, coef0=1.0, gamma=scale, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=1, class_weight=None, coef0=0.1, gamma=auto, kernel=rbf, probability=True; total time=   1.9s
[CV] END C=0.1, class_weight=balanced, coef0=0.0, gamma=auto, kernel=rbf, probability=True; total time=   1.0s
[CV] END C=0.1, class_weight=balanced, coef0=0.0, gamma=auto, kernel=rbf, probability=True; total time=   1.5s
[CV] END C=0.1, class_weight=balanced, coef0=0.0, gamma=auto, kernel=rbf, probability=True; total time=   1.5s
[CV] END C=0.1, class_weight=balanced, coef0=0.0, gamma=auto, kernel=rbf, probability=True; total time=   1.6s
[CV] END C=0.1, class_weight=balanced, coef0=0.0, gamma=auto, kernel=rbf, probability=True; total time=   1.2s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=scale, kernel=linear, probability=True; total time=   0.8s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=scale, kernel=linear, probability=True; total time=   1.0s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=scale, kernel=linear, probability=True; total time=   1.2s
[CV] END C=0.1, class_weight=None, coef0=0.0, gamma=scale, kernel=poly, probability=False; total time=   0.3s
[CV] END C=0.1, class_weight=None, coef0=0.0, gamma=scale, kernel=poly, probability=False; total time=   0.3s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=scale, kernel=linear, probability=True; total time=   0.8s
[CV] END C=0.1, class_weight=None, coef0=0.0, gamma=scale, kernel=poly, probability=False; total time=   0.3s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=scale, kernel=linear, probability=True; total time=   0.9s
[CV] END C=0.1, class_weight=None, coef0=0.0, gamma=scale, kernel=poly, probability=False; total time=   0.2s
[CV] END C=0.1, class_weight=None, coef0=0.0, gamma=scale, kernel=poly, probability=False; total time=   0.3s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=auto, kernel=rbf, probability=True; total time=   1.0s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=auto, kernel=rbf, probability=True; total time=   1.1s
[CV] END C=10, class_weight=None, coef0=1.0, gamma=auto, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=10, class_weight=None, coef0=1.0, gamma=auto, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=10, class_weight=None, coef0=1.0, gamma=auto, kernel=rbf, probability=False; total time=   0.3s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=auto, kernel=rbf, probability=True; total time=   1.8s
[CV] END C=10, class_weight=None, coef0=1.0, gamma=auto, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=10, class_weight=None, coef0=1.0, gamma=auto, kernel=rbf, probability=False; total time=   0.3s
[CV] END C=0.1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=0.1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=auto, kernel=rbf, probability=True; total time=   2.5s
[CV] END C=0.1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=0.1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=rbf, probability=False; total time=   0.2s
[CV] END C=0.1, class_weight=balanced, coef0=0.5, gamma=scale, kernel=rbf, probability=False; total time=   0.3s
[CV] END C=10, class_weight=None, coef0=0.5, gamma=auto, kernel=rbf, probability=True; total time=   2.0s

RandomizedSearchCV(cv=5, estimator=SVC(random_state=42), n_iter=20, n_jobs=-1,
                   param_distributions={'C': [0.1, 1, 10],
                                        'class_weight': [None, 'balanced'],
                                        'coef0': [0.0, 0.1, 0.5, 1.0],
                                        'gamma': ['scale', 'auto'],
                                        'kernel': ['linear', 'rbf', 'poly'],
                                        'probability': [True, False]},
                   random_state=42, scoring='accuracy', verbose=2)

In [20]:
print("Best Hyperparameters:")
print(searcher.best_params_)

print("Best CV Score:")
print(searcher.best_score_)

Best Hyperparameters:
{'probability': True, 'kernel': 'linear', 'gamma': 'auto', 'coef0': 0.5, 'class_weight': None, 'C': 10}
Best CV Score:
0.96

In [21]:
best_model = searcher.best_estimator_
best_model

SVC(C=10, coef0=0.5, gamma='auto', kernel='linear', probability=True,
    random_state=42)

In [22]:
pred = best_model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

Test Accuracy: 97.50%

In [23]:
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier

pipeline = Pipeline([
    ('scalar', StandardScaler()),
    ('dt', DecisionTreeClassifier(random_state=42))
])


pipeline

Pipeline(steps=[('scalar', StandardScaler()),
                ('dt', DecisionTreeClassifier(random_state=42))])

In [24]:
df_dt = df.copy()

DT_X_train, DT_X_test, DT_y_train, DT_y_test = train_test_split(
    df_dt.drop("price_range", axis=1),
    df_dt["price_range"],
    test_size=0.2,
    random_state=42,
)

In [25]:
from sklearn.model_selection import GridSearchCV

searcher = GridSearchCV(
    estimator=pipeline,
    param_grid={
        "dt__max_depth": [None, 5, 10, 15],
        "dt__min_samples_split": [2, 5, 10],
        "dt__min_samples_leaf": [1, 2, 4],
        "dt__criterion": ["gini", "entropy", "log_loss"],
        "dt__splitter": ["best", "random"],
        
    },
    scoring='accuracy',
    cv=5,
    n_jobs=-1,
    verbose=2
)

searcher

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                       ('dt',
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'dt__criterion': ['gini', 'entropy', 'log_loss'],
                         'dt__max_depth': [None, 5, 10, 15],
                         'dt__min_samples_leaf': [1, 2, 4],
                         'dt__min_samples_split': [2, 5, 10],
                         'dt__splitter': ['best', 'random']},
             scoring='accuracy', verbose=2)

In [26]:
searcher.fit(DT_X_train, DT_y_train)

Fitting 5 folds for each of 216 candidates, totalling 1080 fits
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=random; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=10, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=10, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=10, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=5, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=10, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=5, dt__splitter=best; total time=   0.1s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=None, dt__min_samples_leaf=4, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s

[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s

[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=2, dt__splitter=random; total time=   0.0s[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s

[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=5, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=2, dt__min_samples_split=10, dt__splitter=best; total time=   0.0s
[CV] END dt__criterion=gini, dt__max_depth=5, dt__min_samples_leaf=1, dt__min_samples_split=10, dt__splitter=random; total time=   0.0s

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                       ('dt',
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'dt__criterion': ['gini', 'entropy', 'log_loss'],
                         'dt__max_depth': [None, 5, 10, 15],
                         'dt__min_samples_leaf': [1, 2, 4],
                         'dt__min_samples_split': [2, 5, 10],
                         'dt__splitter': ['best', 'random']},
             scoring='accuracy', verbose=2)

In [27]:
print(f"best params : {searcher.best_params_}")
print(f"best score : {searcher.best_score_}")
pipeline = searcher.best_estimator_

best params : {'dt__criterion': 'entropy', 'dt__max_depth': None, 'dt__min_samples_leaf': 2, 'dt__min_samples_split': 5, 'dt__splitter': 'best'}
best score : 0.85875

In [28]:
pipeline

Pipeline(steps=[('scalar', StandardScaler()),
                ('dt',
                 DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                                        min_samples_split=5,
                                        random_state=42))])

In [29]:
pred = pipeline.predict(DT_X_test)

accuracy = accuracy_score(DT_y_test, pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

Test Accuracy: 85.25%

In [30]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(random_state=42)
lr_model

LogisticRegression(random_state=42)

In [32]:
searcher = RandomizedSearchCV(
    estimator=lr_model,
    param_distributions={
        "C": [0.01, 0.1, 1, 10, 100],
        "penalty": ["l1", "l2", "elasticnet", "none"],
        "solver": ["newton-cg", "lbfgs", "liblinear", "sag", "saga"],
        "max_iter": [100, 200, 300, 400, 500]
    },
    scoring='accuracy',
    n_iter=30,
    cv=5,
    n_jobs=-1,
    verbose=2
)

In [33]:
searcher.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits
[CV] END .........C=10, max_iter=400, penalty=l1, solver=sag; total time=   0.0s
[CV] END .........C=10, max_iter=400, penalty=l1, solver=sag; total time=   0.0s
[CV] END .........C=10, max_iter=400, penalty=l1, solver=sag; total time=   0.0s
[CV] END .........C=10, max_iter=400, penalty=l1, solver=sag; total time=   0.0s
[CV] END .........C=10, max_iter=400, penalty=l1, solver=sag; total time=   0.0s
[CV] END ....C=1, max_iter=200, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END ....C=1, max_iter=200, penalty=l1, solver=liblinear; total time=   0.0s[CV] END ....C=1, max_iter=200, penalty=l1, solver=liblinear; total time=   0.0s

[CV] END ....C=1, max_iter=200, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1, max_iter=200, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1, max_iter=200, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END ....C=1, max_iter=200, penalty=l1, solver=liblinear; total time=   0.0s
[CV] END C=1, max_iter=200, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1, max_iter=200, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END C=1, max_iter=200, penalty=elasticnet, solver=liblinear; total time=   0.0s
[CV] END .....C=10, max_iter=400, penalty=none, solver=lbfgs; total time=   0.0s
[CV] END .....C=10, max_iter=400, penalty=none, solver=lbfgs; total time=   0.0s
[CV] END .....C=10, max_iter=400, penalty=none, solver=lbfgs; total time=   0.0s
[CV] END .....C=10, max_iter=400, penalty=none, solver=lbfgs; total time=   0.0s
[CV] END ........C=0.1, max_iter=100, penalty=l1, solver=sag; total time=   0.0s
[CV] END .....C=10, max_iter=400, penalty=none, solver=lbfgs; total time=   0.0s
[CV] END ........C=0.1, max_iter=100, penalty=l1, solver=sag; total time=   0.0s
[CV] END ........C=0.1, max_iter=100, penalty=l1, solver=sag; total time=   0.0s
[CV] END ........C=0.1, max_iter=100, penalty=l1, solver=sag; total time=   0.0s
[CV] END ........C=0.1, max_iter=100, penalty=l1, solver=sag; total time=   0.0s
[CV] END ......C=10, max_iter=200, penalty=none, solver=saga; total time=   0.0s
[CV] END ......C=10, max_iter=200, penalty=none, solver=saga; total time=   0.0s
[CV] END ....C=1, max_iter=400, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ......C=10, max_iter=200, penalty=none, solver=saga; total time=   0.0s
[CV] END ....C=1, max_iter=400, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ......C=10, max_iter=200, penalty=none, solver=saga; total time=   0.0s
[CV] END ....C=1, max_iter=400, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ......C=10, max_iter=200, penalty=none, solver=saga; total time=   0.0s
[CV] END ....C=1, max_iter=400, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ....C=1, max_iter=400, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ........C=100, max_iter=100, penalty=l1, solver=sag; total time=   0.0s
[CV] END ........C=100, max_iter=100, penalty=l1, solver=sag; total time=   0.0s
[CV] END ........C=100, max_iter=100, penalty=l1, solver=sag; total time=   0.0s
[CV] END ........C=100, max_iter=100, penalty=l1, solver=sag; total time=   0.0s
[CV] END ..C=1, max_iter=400, penalty=none, solver=liblinear; total time=   0.0s
[CV] END ........C=100, max_iter=100, penalty=l1, solver=sag; total time=   0.0s
[CV] END ..C=1, max_iter=400, penalty=none, solver=liblinear; total time=   0.0s
[CV] END ..C=1, max_iter=400, penalty=none, solver=liblinear; total time=   0.0s
[CV] END ..C=1, max_iter=400, penalty=none, solver=liblinear; total time=   0.0s
[CV] END ..C=1, max_iter=400, penalty=none, solver=liblinear; total time=   0.0s
[CV] END ......C=100, max_iter=500, penalty=l2, solver=lbfgs; total time=   0.2s
[CV] END ......C=100, max_iter=500, penalty=l2, solver=lbfgs; total time=   0.2s
[CV] END ......C=100, max_iter=500, penalty=l2, solver=lbfgs; total time=   0.2s
[CV] END C=10, max_iter=200, penalty=elasticnet, solver=saga; total time=   0.3s
[CV] END ......C=100, max_iter=500, penalty=l2, solver=lbfgs; total time=   0.1s
[CV] END ......C=100, max_iter=500, penalty=l2, solver=lbfgs; total time=   0.1s
[CV] END C=10, max_iter=200, penalty=elasticnet, solver=saga; total time=   0.3s
[CV] END ....C=1, max_iter=300, penalty=l2, solver=newton-cg; total time=   0.1s
[CV] END .......C=0.01, max_iter=200, penalty=l2, solver=sag; total time=   0.0s
[CV] END .......C=0.01, max_iter=200, penalty=l2, solver=sag; total time=   0.1s
[CV] END .......C=0.01, max_iter=200, penalty=l2, solver=sag; total time=   0.1s
[CV] END C=10, max_iter=200, penalty=elasticnet, solver=saga; total time=   0.8s
[CV] END .......C=0.01, max_iter=200, penalty=l2, solver=sag; total time=   0.0s
[CV] END .......C=0.01, max_iter=200, penalty=l2, solver=sag; total time=   0.0s
[CV] END ....C=0.01, max_iter=100, penalty=none, solver=saga; total time=   0.0s
[CV] END ....C=0.01, max_iter=100, penalty=none, solver=saga; total time=   0.0s
[CV] END ....C=0.01, max_iter=100, penalty=none, solver=saga; total time=   0.0s
[CV] END ....C=0.01, max_iter=100, penalty=none, solver=saga; total time=   0.0s
[CV] END ....C=0.01, max_iter=100, penalty=none, solver=saga; total time=   0.0s
[CV] END C=10, max_iter=200, penalty=elasticnet, solver=saga; total time=   0.3s
[CV] END ........C=100, max_iter=300, penalty=l2, solver=sag; total time=   1.1s
[CV] END ........C=100, max_iter=300, penalty=l2, solver=sag; total time=   0.3s
[CV] END C=0.01, max_iter=400, penalty=none, solver=liblinear; total time=   0.0s
[CV] END C=0.01, max_iter=400, penalty=none, solver=liblinear; total time=   0.0s
[CV] END C=0.01, max_iter=400, penalty=none, solver=liblinear; total time=   0.0s
[CV] END C=0.01, max_iter=400, penalty=none, solver=liblinear; total time=   0.0s
[CV] END C=0.01, max_iter=400, penalty=none, solver=liblinear; total time=   0.0s
[CV] END .....C=100, max_iter=200, penalty=none, solver=saga; total time=   0.0s
[CV] END .....C=100, max_iter=200, penalty=none, solver=saga; total time=   0.0s
[CV] END .....C=100, max_iter=200, penalty=none, solver=saga; total time=   0.0s
[CV] END .....C=100, max_iter=200, penalty=none, solver=saga; total time=   0.0s
[CV] END .....C=100, max_iter=200, penalty=none, solver=saga; total time=   0.0s
[CV] END ...C=10, max_iter=500, penalty=l2, solver=newton-cg; total time=   0.0s
[CV] END ...C=10, max_iter=500, penalty=l2, solver=newton-cg; total time=   0.0s
[CV] END ........C=100, max_iter=500, penalty=l2, solver=sag; total time=   0.5s
[CV] END ...C=10, max_iter=500, penalty=l2, solver=newton-cg; total time=   0.1s
[CV] END ...C=10, max_iter=500, penalty=l2, solver=newton-cg; total time=   0.1s
[CV] END ...C=10, max_iter=500, penalty=l2, solver=newton-cg; total time=   0.1s
[CV] END .C=10, max_iter=400, penalty=none, solver=newton-cg; total time=   0.0s
[CV] END .C=10, max_iter=400, penalty=none, solver=newton-cg; total time=   0.0s
[CV] END .C=10, max_iter=400, penalty=none, solver=newton-cg; total time=   0.0s
[CV] END .C=10, max_iter=400, penalty=none, solver=newton-cg; total time=   0.0s
[CV] END .C=10, max_iter=400, penalty=none, solver=newton-cg; total time=   0.0s
[CV] END .......C=1, max_iter=300, penalty=none, solver=saga; total time=   0.0s
[CV] END .......C=1, max_iter=300, penalty=none, solver=saga; total time=   0.0s
[CV] END .......C=1, max_iter=300, penalty=none, solver=saga; total time=   0.0s
[CV] END .......C=1, max_iter=300, penalty=none, solver=saga; total time=   0.0s
[CV] END .......C=1, max_iter=300, penalty=none, solver=saga; total time=   0.0s
[CV] END C=10, max_iter=300, penalty=elasticnet, solver=newton-cg; total time=   0.0s
[CV] END C=10, max_iter=300, penalty=elasticnet, solver=newton-cg; total time=   0.0s
[CV] END C=10, max_iter=300, penalty=elasticnet, solver=newton-cg; total time=   0.0s
[CV] END C=10, max_iter=300, penalty=elasticnet, solver=newton-cg; total time=   0.0s
[CV] END C=10, max_iter=300, penalty=elasticnet, solver=newton-cg; total time=   0.0s
[CV] END .....C=0.1, max_iter=400, penalty=none, solver=saga; total time=   0.0s
[CV] END .....C=0.1, max_iter=400, penalty=none, solver=saga; total time=   0.0s
[CV] END .....C=0.1, max_iter=400, penalty=none, solver=saga; total time=   0.0s
[CV] END .....C=0.1, max_iter=400, penalty=none, solver=saga; total time=   0.0s
[CV] END .....C=0.1, max_iter=400, penalty=none, solver=saga; total time=   0.0s
[CV] END C=0.01, max_iter=400, penalty=none, solver=newton-cg; total time=   0.0s
[CV] END C=0.01, max_iter=400, penalty=none, solver=newton-cg; total time=   0.0s
[CV] END C=0.01, max_iter=400, penalty=none, solver=newton-cg; total time=   0.0s
[CV] END C=0.01, max_iter=400, penalty=none, solver=newton-cg; total time=   0.0s
[CV] END C=0.01, max_iter=400, penalty=none, solver=newton-cg; total time=   0.0s
[CV] END C=10, max_iter=200, penalty=elasticnet, solver=saga; total time=   1.0s
[CV] END ........C=100, max_iter=300, penalty=l2, solver=sag; total time=   0.7s
[CV] END ........C=100, max_iter=500, penalty=l2, solver=sag; total time=   0.5s
[CV] END ........C=100, max_iter=300, penalty=l2, solver=sag; total time=   0.4s
[CV] END C=100, max_iter=300, penalty=elasticnet, solver=saga; total time=   0.6s
[CV] END ........C=100, max_iter=500, penalty=l2, solver=sag; total time=   0.5s
[CV] END C=100, max_iter=300, penalty=elasticnet, solver=saga; total time=   0.8s
[CV] END ........C=100, max_iter=300, penalty=l2, solver=sag; total time=   0.5s
[CV] END ....C=1, max_iter=300, penalty=l2, solver=newton-cg; total time=   0.1s
[CV] END ....C=1, max_iter=300, penalty=l2, solver=newton-cg; total time=   0.1s
[CV] END ....C=1, max_iter=300, penalty=l2, solver=newton-cg; total time=   0.1s
[CV] END C=100, max_iter=300, penalty=elasticnet, solver=saga; total time=   0.6s
[CV] END C=100, max_iter=300, penalty=elasticnet, solver=saga; total time=   0.7s
[CV] END ..C=100, max_iter=300, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ..C=100, max_iter=300, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ..C=100, max_iter=300, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ..C=100, max_iter=300, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END ....C=1, max_iter=300, penalty=l2, solver=newton-cg; total time=   0.2s
[CV] END ..C=100, max_iter=300, penalty=l2, solver=liblinear; total time=   0.0s
[CV] END .C=0.01, max_iter=400, penalty=l1, solver=newton-cg; total time=   0.0s
[CV] END .C=0.01, max_iter=400, penalty=l1, solver=newton-cg; total time=   0.0s[CV] END .C=0.01, max_iter=400, penalty=l1, solver=newton-cg; total time=   0.0s

[CV] END .C=0.01, max_iter=400, penalty=l1, solver=newton-cg; total time=   0.0s
[CV] END .C=0.01, max_iter=400, penalty=l1, solver=newton-cg; total time=   0.0s
[CV] END .......C=0.01, max_iter=400, penalty=l1, solver=sag; total time=   0.0s
[CV] END .......C=0.01, max_iter=400, penalty=l1, solver=sag; total time=   0.0s
[CV] END .......C=0.01, max_iter=400, penalty=l1, solver=sag; total time=   0.0s
[CV] END .......C=0.01, max_iter=400, penalty=l1, solver=sag; total time=   0.0s
[CV] END .......C=0.01, max_iter=400, penalty=l1, solver=sag; total time=   0.0s
[CV] END ......C=10, max_iter=100, penalty=none, solver=saga; total time=   0.0s
[CV] END ......C=10, max_iter=100, penalty=none, solver=saga; total time=   0.0s
[CV] END ........C=100, max_iter=500, penalty=l2, solver=sag; total time=   0.8s
[CV] END ......C=10, max_iter=100, penalty=none, solver=saga; total time=   0.0s
[CV] END ......C=10, max_iter=100, penalty=none, solver=saga; total time=   0.0s
[CV] END .....C=10, max_iter=100, penalty=none, solver=lbfgs; total time=   0.0s
[CV] END ......C=10, max_iter=100, penalty=none, solver=saga; total time=   0.0s
[CV] END .....C=10, max_iter=100, penalty=none, solver=lbfgs; total time=   0.0s
[CV] END .....C=10, max_iter=100, penalty=none, solver=lbfgs; total time=   0.0s
[CV] END .....C=10, max_iter=100, penalty=none, solver=lbfgs; total time=   0.0s[CV] END .....C=10, max_iter=100, penalty=none, solver=lbfgs; total time=   0.0s

[CV] END C=100, max_iter=300, penalty=elasticnet, solver=saga; total time=   0.5s
[CV] END ........C=100, max_iter=500, penalty=l2, solver=sag; total time=   0.5s

RandomizedSearchCV(cv=5, estimator=LogisticRegression(random_state=42),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'C': [0.01, 0.1, 1, 10, 100],
                                        'max_iter': [100, 200, 300, 400, 500],
                                        'penalty': ['l1', 'l2', 'elasticnet',
                                                    'none'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy', verbose=2)

In [34]:
print("Best Hyperparameters:")
print(searcher.best_params_)
print("Best CV Score:")
print(searcher.best_score_)
lr_model = searcher.best_estimator_

Best Hyperparameters:
{'solver': 'sag', 'penalty': 'l2', 'max_iter': 300, 'C': 100}
Best CV Score:
0.963125

In [35]:
lr_model

LogisticRegression(C=100, max_iter=300, penalty='l2', random_state=42,
                   solver='sag')

In [36]:
lr_pred = lr_model.predict(X_test)
accuracy = accuracy_score(y_test, lr_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

Test Accuracy: 98.00%

## Ensemble Learning

## Stacking as ensemble learning

In [38]:
base_models = {
    'lr' : LogisticRegression(random_state=42, solver = "sag", penalty= 'l2', max_iter=300, C=100),
    'dt' : DecisionTreeClassifier(random_state=42, criterion= "entropy", max_depth= None, min_samples_leaf= 2, min_samples_split= 5, splitter= "best"),
    'svm' : SVC(random_state=42, C=10, kernel= 'linear', gamma= 'auto', class_weight= None, coef0= 0.5, probability= True)
}

connector = LogisticRegression(random_state=42, solver = "sag", penalty= 'l2', max_iter=300, C=100)

In [39]:
from sklearn.ensemble import StackingClassifier

stacking_model = StackingClassifier(estimators=list(base_models.items()), final_estimator= connector, cv= 5)
stacking_model

StackingClassifier(cv=5,
                   estimators=[('lr',
                                LogisticRegression(C=100, max_iter=300,
                                                   penalty='l2',
                                                   random_state=42,
                                                   solver='sag')),
                               ('dt',
                                DecisionTreeClassifier(criterion='entropy',
                                                       min_samples_leaf=2,
                                                       min_samples_split=5,
                                                       random_state=42)),
                               ('svm',
                                SVC(C=10, coef0=0.5, gamma='auto',
                                    kernel='linear', probability=True,
                                    random_state=42))],
                   final_estimator=LogisticRegression(C=100, max_iter=300,
                                                      penalty='l2',
                                                      random_state=42,
                                                      solver='sag'))

In [40]:
stacking_model.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('lr',
                                LogisticRegression(C=100, max_iter=300,
                                                   penalty='l2',
                                                   random_state=42,
                                                   solver='sag')),
                               ('dt',
                                DecisionTreeClassifier(criterion='entropy',
                                                       min_samples_leaf=2,
                                                       min_samples_split=5,
                                                       random_state=42)),
                               ('svm',
                                SVC(C=10, coef0=0.5, gamma='auto',
                                    kernel='linear', probability=True,
                                    random_state=42))],
                   final_estimator=LogisticRegression(C=100, max_iter=300,
                                                      penalty='l2',
                                                      random_state=42,
                                                      solver='sag'))

In [41]:
stack_pred = stacking_model.predict(X_test)
accuracy = accuracy_score(y_test, stack_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

Test Accuracy: 97.50%

**It is just for learning how stacking Works**

In [ ]:
stack_