In [5]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

sns.set_style('whitegrid')
sns.set_palette('Set2')
sns.set_context('notebook', font_scale=1.5, rc={"lines.linewidth": 2.5})
sns.set_style('ticks')

In [6]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

file_path = "train.csv"

df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS,
    "iabhishekofficial/mobile-price-classification",
    file_path
)

Downloading to /root/.cache/kagglehub/datasets/iabhishekofficial/mobile-price-classification/versions/1/train.csv...

100%|██████████| 120k/120k [00:00<00:00, 649kB/s]

In [7]:
df.head()

   battery_power  blue  clock_speed  ...  touch_screen  wifi  price_range
0            842     0          2.2  ...             0     1            1
1           1021     1          0.5  ...             1     0            2
2            563     1          0.5  ...             1     0            2
3            615     1          2.5  ...             0     0            2
4           1821     1          1.2  ...             1     0            1

[5 rows x 21 columns]

In [8]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [9]:
df.shape

(2000, 21)

In [10]:
df['price_range'].value_counts()

price_range
1    500
2    500
3    500
0    500
Name: count, dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  2000 non-null   int64
 1   blue           2000 non-null   int64
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64
 4   fc             2000 non-null   int64
 5   four_g         2000 non-null   int64
 6   int_memory     2000 non-null   int64
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64
 9   n_cores        2000 non-null   int64
 10  pc             2000 non-null   int64
 11  px_height      2000 non-null   int64
 12  px_width       2000 non-null   int64
 13  ram            2000 non-null   int64
 14  sc_h           2000 non-null   int64
 15  sc_w           2000 non-null   int64
 16  talk_time      2000 non-null   int64
 17  three_g        2000 non-null   int64
 18  touch_screen   2000 non-null   int64
 19  wifi           2000 non-null   int64
 20  price_range    2000 non-null   int64
dtypes: float64(2), int64(19)
memory usage: 328.3 KB

In [12]:
df.describe()

       battery_power       blue  ...         wifi  price_range
count    2000.000000  2000.0000  ...  2000.000000  2000.000000
mean     1238.518500     0.4950  ...     0.507000     1.500000
std       439.418206     0.5001  ...     0.500076     1.118314
min       501.000000     0.0000  ...     0.000000     0.000000
25%       851.750000     0.0000  ...     0.000000     0.750000
50%      1226.000000     0.0000  ...     1.000000     1.500000
75%      1615.250000     1.0000  ...     1.000000     2.250000
max      1998.000000     1.0000  ...     1.000000     3.000000

[8 rows x 21 columns]

In [13]:
from sklearn.model_selection import train_test_split

X = df.drop("price_range", axis=1)
y = df["price_range"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [14]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1600, 20), (400, 20), (1600,), (400,))

In [15]:
X_train

      battery_power  blue  clock_speed  ...  three_g  touch_screen  wifi
469            1845     1          0.5  ...        0             0     0
565            1271     1          0.5  ...        0             0     1
396             788     0          2.5  ...        1             1     1
452            1406     0          0.5  ...        1             0     1
325             920     0          2.1  ...        0             1     1
...             ...   ...          ...  ...      ...           ...   ...
1170           1100     1          1.6  ...        1             1     1
100            1883     1          0.5  ...        1             0     0
63             1720     0          2.0  ...        1             1     1
180             703     1          2.7  ...        1             0     0
876            1064     0          2.9  ...        1             0     0

[1600 rows x 20 columns]

In [16]:
from sklearn.svm import SVC

In [17]:
base_model = SVC(random_state=42)
base_model

SVC(random_state=42)

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
scores = cross_val_score(base_model, X_train, y_train, cv=5, scoring='accuracy')
print(scores.mean())
scores

0.859375

array([0.853125, 0.871875, 0.840625, 0.85    , 0.88125 ])

In [21]:
from sklearn.model_selection import RandomizedSearchCV

param_dist = {

    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto'],
    'class_weight': [None, 'balanced'],
    'coef0': [0.0, 0.1, 0.5, 1.0],
    'probability': [True, False]

}

searcher = RandomizedSearchCV(

    estimator=base_model,
    param_distributions=param_dist,
    n_iter=20,
    scoring='accuracy',
    cv=5,
    random_state=42,
    n_jobs=-1,
    verbose=2
)

In [22]:
searcher.fit(X_train, y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5, estimator=SVC(random_state=42), n_iter=20, n_jobs=-1,
                   param_distributions={'C': [0.1, 1, 10],
                                        'class_weight': [None, 'balanced'],
                                        'coef0': [0.0, 0.1, 0.5, 1.0],
                                        'gamma': ['scale', 'auto'],
                                        'kernel': ['linear', 'rbf', 'poly'],
                                        'probability': [True, False]},
                   random_state=42, scoring='accuracy', verbose=2)

In [23]:
print("Best Hyperparameters:")
print(searcher.best_params_)

print("Best CV Score:")
print(searcher.best_score_)

Best Hyperparameters:
{'probability': True, 'kernel': 'linear', 'gamma': 'auto', 'coef0': 0.5, 'class_weight': None, 'C': 10}
Best CV Score:
0.96

In [24]:
best_model = searcher.best_estimator_
best_model

SVC(C=10, coef0=0.5, gamma='auto', kernel='linear', probability=True,
    random_state=42)

In [25]:
pred = best_model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

Test Accuracy: 97.50%

In [26]:
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier

pipeline = Pipeline([
    ('scalar', StandardScaler()),
    ('dt', DecisionTreeClassifier(random_state=42))
])


pipeline

Pipeline(steps=[('scalar', StandardScaler()),
                ('dt', DecisionTreeClassifier(random_state=42))])

In [27]:
df_dt = df.copy()

DT_X_train, DT_X_test, DT_y_train, DT_y_test = train_test_split(
    df_dt.drop("price_range", axis=1),
    df_dt["price_range"],
    test_size=0.2,
    random_state=42,
)

In [28]:
from sklearn.model_selection import GridSearchCV

searcher = GridSearchCV(
    estimator=pipeline,
    param_grid={
        "dt__max_depth": [None, 5, 10, 15],
        "dt__min_samples_split": [2, 5, 10],
        "dt__min_samples_leaf": [1, 2, 4],
        "dt__criterion": ["gini", "entropy", "log_loss"],
        "dt__splitter": ["best", "random"],

    },
    scoring='accuracy',
    cv=5,
    n_jobs=-1,
    verbose=2
)

searcher

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                       ('dt',
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'dt__criterion': ['gini', 'entropy', 'log_loss'],
                         'dt__max_depth': [None, 5, 10, 15],
                         'dt__min_samples_leaf': [1, 2, 4],
                         'dt__min_samples_split': [2, 5, 10],
                         'dt__splitter': ['best', 'random']},
             scoring='accuracy', verbose=2)

In [29]:
searcher.fit(DT_X_train, DT_y_train)

Fitting 5 folds for each of 216 candidates, totalling 1080 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                       ('dt',
                                        DecisionTreeClassifier(random_state=42))]),
             n_jobs=-1,
             param_grid={'dt__criterion': ['gini', 'entropy', 'log_loss'],
                         'dt__max_depth': [None, 5, 10, 15],
                         'dt__min_samples_leaf': [1, 2, 4],
                         'dt__min_samples_split': [2, 5, 10],
                         'dt__splitter': ['best', 'random']},
             scoring='accuracy', verbose=2)

In [30]:
print(f"best params : {searcher.best_params_}")
print(f"best score : {searcher.best_score_}")
pipeline = searcher.best_estimator_

best params : {'dt__criterion': 'entropy', 'dt__max_depth': None, 'dt__min_samples_leaf': 2, 'dt__min_samples_split': 5, 'dt__splitter': 'best'}
best score : 0.85875

In [31]:
pipeline

Pipeline(steps=[('scalar', StandardScaler()),
                ('dt',
                 DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                                        min_samples_split=5,
                                        random_state=42))])

In [32]:
pred = pipeline.predict(DT_X_test)

accuracy = accuracy_score(DT_y_test, pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

Test Accuracy: 85.25%

In [33]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression(random_state=42)
lr_model

LogisticRegression(random_state=42)

In [34]:
searcher = RandomizedSearchCV(
    estimator=lr_model,
    param_distributions={
        "C": [0.01, 0.1, 1, 10, 100],
        "penalty": ["l1", "l2", "elasticnet", "none"],
        "solver": ["newton-cg", "lbfgs", "liblinear", "sag", "saga"],
        "max_iter": [100, 200, 300, 400, 500]
    },
    scoring='accuracy',
    n_iter=30,
    cv=5,
    n_jobs=-1,
    verbose=2
)

In [35]:
searcher.fit(X_train, y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5, estimator=LogisticRegression(random_state=42),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'C': [0.01, 0.1, 1, 10, 100],
                                        'max_iter': [100, 200, 300, 400, 500],
                                        'penalty': ['l1', 'l2', 'elasticnet',
                                                    'none'],
                                        'solver': ['newton-cg', 'lbfgs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy', verbose=2)

In [36]:
print("Best Hyperparameters:")
print(searcher.best_params_)
print("Best CV Score:")
print(searcher.best_score_)
lr_model = searcher.best_estimator_

Best Hyperparameters:
{'solver': 'sag', 'penalty': 'l2', 'max_iter': 400, 'C': 100}
Best CV Score:
0.9637499999999999

In [37]:
lr_model

LogisticRegression(C=100, max_iter=400, random_state=42, solver='sag')

In [38]:
lr_pred = lr_model.predict(X_test)
accuracy = accuracy_score(y_test, lr_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

Test Accuracy: 98.00%

## Ensemble Learning

## Stacking as ensemble learning

In [39]:
base_models = {
    'lr' : LogisticRegression(random_state=42, solver = "sag", penalty= 'l2', max_iter=300, C=100),
    'dt' : DecisionTreeClassifier(random_state=42, criterion= "entropy", max_depth= None, min_samples_leaf= 2, min_samples_split= 5, splitter= "best"),
    'svm' : SVC(random_state=42, C=10, kernel= 'linear', gamma= 'auto', class_weight= None, coef0= 0.5, probability= True)
}

connector = LogisticRegression(random_state=42, solver = "sag", penalty= 'l2', max_iter=300, C=100)

In [40]:
from sklearn.ensemble import StackingClassifier

stacking_model = StackingClassifier(estimators=list(base_models.items()), final_estimator= connector, cv= 5)
stacking_model

StackingClassifier(cv=5,
                   estimators=[('lr',
                                LogisticRegression(C=100, max_iter=300,
                                                   random_state=42,
                                                   solver='sag')),
                               ('dt',
                                DecisionTreeClassifier(criterion='entropy',
                                                       min_samples_leaf=2,
                                                       min_samples_split=5,
                                                       random_state=42)),
                               ('svm',
                                SVC(C=10, coef0=0.5, gamma='auto',
                                    kernel='linear', probability=True,
                                    random_state=42))],
                   final_estimator=LogisticRegression(C=100, max_iter=300,
                                                      random_state=42,
                                                      solver='sag'))

In [41]:
stacking_model.fit(X_train, y_train)

StackingClassifier(cv=5,
                   estimators=[('lr',
                                LogisticRegression(C=100, max_iter=300,
                                                   random_state=42,
                                                   solver='sag')),
                               ('dt',
                                DecisionTreeClassifier(criterion='entropy',
                                                       min_samples_leaf=2,
                                                       min_samples_split=5,
                                                       random_state=42)),
                               ('svm',
                                SVC(C=10, coef0=0.5, gamma='auto',
                                    kernel='linear', probability=True,
                                    random_state=42))],
                   final_estimator=LogisticRegression(C=100, max_iter=300,
                                                      random_state=42,
                                                      solver='sag'))

In [42]:
stack_pred = stacking_model.predict(X_test)
accuracy = accuracy_score(y_test, stack_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

Test Accuracy: 97.50%

**It is just for learning how stacking Works**

## Bagging (RandomForest)

In [43]:
from sklearn.ensemble import RandomForestClassifier

In [44]:
rf_model = RandomForestClassifier(random_state=42)

In [45]:
pipeline = Pipeline([
    ('scalar', StandardScaler()),
    ('rf', rf_model)
])

In [46]:
df_rf = df.copy()
rf_X_train, rf_X_test, rf_y_train, rf_y_test = train_test_split(
    df_rf.drop("price_range", axis=1),
    df_rf["price_range"],
    test_size=0.2,
    random_state=42,
)

In [47]:
cv_score = cross_val_score(pipeline, rf_X_train, rf_y_train, cv=5, scoring='accuracy')
print(cv_score)
print(f"Cross-Validation Accuracy: {cv_score.mean() * 100:.2f}%")

[0.8875   0.884375 0.88125  0.85625  0.85    ]
Cross-Validation Accuracy: 87.19%

# Hyperparam tuning

In [48]:
selector_rf = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions={
        "rf__n_estimators": [50, 100, 200, 300,500,800,1200],
        "rf__criterion": ["gini", "entropy", "log_loss"],
        "rf__max_depth": [None, 5, 10, 15,20],
        "rf__max_features": ["sqrt", "log2", None],
        "rf__min_samples_split": [2, 5, 10],
        "rf__min_samples_leaf": [1, 2, 4],
        "rf__bootstrap": [True, False]
    },
    n_iter=30,
    scoring='accuracy',
    cv=5,
    n_jobs=-1,
    verbose=2
)

In [49]:
selector_rf.fit(rf_X_train, rf_y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                             ('rf',
                                              RandomForestClassifier(random_state=42))]),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'rf__bootstrap': [True, False],
                                        'rf__criterion': ['gini', 'entropy',
                                                          'log_loss'],
                                        'rf__max_depth': [None, 5, 10, 15, 20],
                                        'rf__max_features': ['sqrt', 'log2',
                                                             None],
                                        'rf__min_samples_leaf': [1, 2, 4],
                                        'rf__min_samples_split': [2, 5, 10],
                                        'rf__n_estimators': [50, 100, 200, 300,
                                                             500, 800, 1200]},
                   scoring='accuracy', verbose=2)

In [50]:
print("Best Hyperparameters:")
print(selector_rf.best_params_)
print("Best CV Score:")
print(selector_rf.best_score_)

Best Hyperparameters:
{'rf__n_estimators': 50, 'rf__min_samples_split': 10, 'rf__min_samples_leaf': 2, 'rf__max_features': None, 'rf__max_depth': 20, 'rf__criterion': 'entropy', 'rf__bootstrap': True}
Best CV Score:
0.891875

In [51]:
main_pipeline = selector_rf.best_estimator_

In [52]:
rf_pred = main_pipeline.predict(rf_X_test)
accuracy = accuracy_score(rf_y_test, rf_pred)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

Test Accuracy: 90.75%

**This is only for learning purpose how RandomForest and bagging works**

## **Boosting**

## AdaBoost

In [53]:
ada_df = df.copy()

In [54]:

ada_X_train, ada_X_test, ada_y_train, ada_y_test = train_test_split(
    ada_df.drop("price_range", axis=1),
    ada_df["price_range"],
    test_size=0.2,
    random_state=42,
)

In [55]:
from sklearn.ensemble import AdaBoostClassifier

ada_pipeline = Pipeline([
    ('scalar', StandardScaler()),
    ('ada', AdaBoostClassifier(random_state=42))
])

In [56]:


ada_score = cross_val_score(ada_pipeline, ada_X_train, ada_y_train, cv=5, scoring='accuracy')

print(ada_score)
print(f"Cross-Validation Accuracy: {ada_score.mean() * 100:.2f}%")

[0.534375 0.553125 0.459375 0.440625 0.56875 ]
Cross-Validation Accuracy: 51.12%

In [57]:
from sklearn.model_selection import RandomizedSearchCV

ada_selector = RandomizedSearchCV(
    estimator=ada_pipeline,
    param_distributions={
        "ada__n_estimators": [50, 100, 200, 300, 500, 800, 1200],
        "ada__learning_rate": [0.01, 0.1, 0.5, 1.0, 1.5, 2.0],
        "ada__random_state": [42]
    },
    n_iter=30,
    scoring='accuracy',
    cv=5,
    n_jobs=-1,
    verbose=2
)

ada_selector.fit(ada_X_train, ada_y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                             ('ada',
                                              AdaBoostClassifier(random_state=42))]),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'ada__learning_rate': [0.01, 0.1, 0.5,
                                                               1.0, 1.5, 2.0],
                                        'ada__n_estimators': [50, 100, 200, 300,
                                                              500, 800, 1200],
                                        'ada__random_state': [42]},
                   scoring='accuracy', verbose=2)

In [58]:
print("Best Hyperparameters:")
print(ada_selector.best_params_)

print("Best CV Score:")
print(ada_selector.best_score_)

ada_pipeline = ada_selector.best_estimator_

Best Hyperparameters:
{'ada__random_state': 42, 'ada__n_estimators': 200, 'ada__learning_rate': 0.1}
Best CV Score:
0.74

In [59]:
ada_pred = ada_pipeline.predict(ada_X_test)
accuracy = accuracy_score(ada_y_test, ada_pred)
print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.745

## Gradient Boost

In [60]:
from sklearn.ensemble import GradientBoostingClassifier

gradient_boosting_pipeline = Pipeline([
    ('scalar', StandardScaler()),
    ('gb', GradientBoostingClassifier(random_state=42))
])

gradient_boosting_score = cross_val_score(gradient_boosting_pipeline, ada_X_train, ada_y_train, cv=5, scoring='accuracy')
print(f"Gradient Boosting Cross-Validation Scores: {gradient_boosting_score}")
print(f"Gradient Boosting Cross-Validation Accuracy: {gradient_boosting_score.mean() * 100:.2f}%")

Gradient Boosting Cross-Validation Scores: [0.884375 0.915625 0.890625 0.8875   0.890625]
Gradient Boosting Cross-Validation Accuracy: 89.38%

In [61]:
gradient_selector = RandomizedSearchCV(
    estimator=gradient_boosting_pipeline,
    param_distributions={
        "gb__n_estimators": [50, 100, 200, 300, 500, 800, 1200],
        "gb__learning_rate": [0.01, 0.1, 0.5, 1.0, 1.5, 2.0],
        "gb__max_depth": [3, 5, 7, 10, 15],
        "gb__min_samples_split": [2, 5, 10],
        "gb__min_samples_leaf": [1, 2, 4],
        "gb__subsample": [0.5, 0.7, 1.0],
        "gb__max_features": ["sqrt", "log2", None]
    },
    n_iter=30,
    scoring='accuracy',
    cv=5,
    n_jobs=-1,
    verbose=2
)
gradient_selector

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                             ('gb',
                                              GradientBoostingClassifier(random_state=42))]),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'gb__learning_rate': [0.01, 0.1, 0.5,
                                                              1.0, 1.5, 2.0],
                                        'gb__max_depth': [3, 5, 7, 10, 15],
                                        'gb__max_features': ['sqrt', 'log2',
                                                             None],
                                        'gb__min_samples_leaf': [1, 2, 4],
                                        'gb__min_samples_split': [2, 5, 10],
                                        'gb__n_estimators': [50, 100, 200, 300,
                                                             500, 800, 1200],
                                        'gb__subsample': [0.5, 0.7, 1.0]},
                   scoring='accuracy', verbose=2)

In [62]:
gradient_selector.fit(ada_X_train, ada_y_train)

Fitting 5 folds for each of 30 candidates, totalling 150 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                             ('gb',
                                              GradientBoostingClassifier(random_state=42))]),
                   n_iter=30, n_jobs=-1,
                   param_distributions={'gb__learning_rate': [0.01, 0.1, 0.5,
                                                              1.0, 1.5, 2.0],
                                        'gb__max_depth': [3, 5, 7, 10, 15],
                                        'gb__max_features': ['sqrt', 'log2',
                                                             None],
                                        'gb__min_samples_leaf': [1, 2, 4],
                                        'gb__min_samples_split': [2, 5, 10],
                                        'gb__n_estimators': [50, 100, 200, 300,
                                                             500, 800, 1200],
                                        'gb__subsample': [0.5, 0.7, 1.0]},
                   scoring='accuracy', verbose=2)

In [63]:
print("Best Hyperparameters:")
print(gradient_selector.best_params_)

print("Best CV Score:")
print(gradient_selector.best_score_)

gradient_pipeline = gradient_selector.best_estimator_

Best Hyperparameters:
{'gb__subsample': 1.0, 'gb__n_estimators': 800, 'gb__min_samples_split': 5, 'gb__min_samples_leaf': 4, 'gb__max_features': None, 'gb__max_depth': 3, 'gb__learning_rate': 0.01}
Best CV Score:
0.8956249999999999

In [64]:
gradient_pred = gradient_pipeline.predict(ada_X_test)
accuracy = accuracy_score(ada_y_test, gradient_pred)
print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.9025

## XGBoost

In [65]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.13/dist-packages (3.4.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from xgboost) (1.16.3)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost) (2.31.2)

In [66]:
from xgboost import XGBClassifier

In [67]:
xg_pipeline = Pipeline(
    [
        ('scalar', StandardScaler()),
        ('xg', XGBClassifier(random_state=42))
    ]
)
xg_pipeline

Pipeline(steps=[('scalar', StandardScaler()),
                ('xg',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=None, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=True, eval_metric=None,
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=None,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=None, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=None, n_jobs=None,
                               num_parallel_tree=None, ...))])

In [68]:
xg_scores = cross_val_score(xg_pipeline, ada_X_train, ada_y_train, cv=5, scoring='accuracy')
print(f"XGBoost score cv : {xg_scores}")
print(f"XGBoost mean score cv : {xg_scores.mean()}")

XGBoost score cv : [0.90625  0.915625 0.9      0.890625 0.9125  ]
XGBoost mean score cv : 0.9049999999999999

In [74]:
xg_selector = RandomizedSearchCV(
    estimator=xg_pipeline,
    param_distributions={
        "xg__n_estimators": [50, 100, 200, 300, 400, 600, 800, 1200],
        "xg__booster" : ['gbtree', 'gblinear', 'dart'],
        "xg__eta": [0.01, 0.5, 0.1,],
        "xg__max_depth": [3, 5, 7, 10, 15],
        "xg__min_child_weight": [1, 2, 5, 10, 20],
        "xg__subsample": [0.5, 0.7, 1.0],
        "xg__colsample_bytree": [0.5, 0.7, 1.0],
        "xg__verbosity" : [0,1,2,3],
        "xg__alpha" : [0,1,2,3,4,5,6,7,8,9,10],
        "xg__lambda" : [0,1,2,3,4,5,6,7,8,9,10]
    },
    n_iter=50,
    scoring='accuracy',
    cv = 5,
    verbose = 1,
    random_state = 42
)

In [75]:
xg_selector.fit(ada_X_train, ada_y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits
[14:14:50] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:50] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:50] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:51] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:51] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:51] ======== Monitor (0): HostSketchContainer ========
[14:14:51] AllReduce: 0.000354s, 1 calls @ 354us

[14:14:51] MakeCuts: 0.0004s, 1 calls @ 400us

[14:14:51] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:51] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:14:51] ======== Monitor (0): GBTree ========
[14:14:51] BoostNewTrees: 0.061272s, 100 calls @ 61272us

[14:14:51] CommitModel: 2.5e-05s, 100 calls @ 25us

[14:14:51] ======== Monitor (0): HistUpdater ========
[14:14:51] BuildHistogram: 0.014747s, 782 calls @ 14747us

[14:14:51] EvaluateSplits: 0.013166s, 1182 calls @ 13166us

[14:14:51] InitData: 0.003801s, 400 calls @ 3801us

[14:14:51] InitRoot: 0.011882s, 400 calls @ 11882us

[14:14:51] LeafPartition: 0.003154s, 400 calls @ 3154us

[14:14:51] UpdatePosition: 0.009701s, 1150 calls @ 9701us

[14:14:51] UpdateTree: 0.055209s, 400 calls @ 55209us

[14:14:51] ======== Monitor (0):  ========
[14:14:51] BuildHist: 0.013629s, 1182 calls @ 13629us

[14:14:51] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:14:51] ======== Monitor (0): HostSketchContainer ========
[14:14:51] AllReduce: 0.000346s, 1 calls @ 346us

[14:14:51] MakeCuts: 0.000391s, 1 calls @ 391us

[14:14:51] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:51] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:14:51] ======== Monitor (0): GBTree ========
[14:14:51] BoostNewTrees: 0.061385s, 100 calls @ 61385us

[14:14:51] CommitModel: 3.1e-05s, 100 calls @ 31us

[14:14:51] ======== Monitor (0): HistUpdater ========
[14:14:51] BuildHistogram: 0.014661s, 781 calls @ 14661us

[14:14:51] EvaluateSplits: 0.013324s, 1181 calls @ 13324us

[14:14:51] InitData: 0.003801s, 400 calls @ 3801us

[14:14:51] InitRoot: 0.011844s, 400 calls @ 11844us

[14:14:51] LeafPartition: 0.003087s, 400 calls @ 3087us

[14:14:51] UpdatePosition: 0.009741s, 1154 calls @ 9741us

[14:14:51] UpdateTree: 0.055265s, 400 calls @ 55265us

[14:14:51] ======== Monitor (0):  ========
[14:14:51] BuildHist: 0.013571s, 1181 calls @ 13571us

[14:14:51] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:14:51] ======== Monitor (0): HostSketchContainer ========
[14:14:51] AllReduce: 0.000336s, 1 calls @ 336us

[14:14:51] MakeCuts: 0.000381s, 1 calls @ 381us

[14:14:51] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:51] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:14:51] ======== Monitor (0): GBTree ========
[14:14:51] BoostNewTrees: 0.063594s, 100 calls @ 63594us

[14:14:51] CommitModel: 2.8e-05s, 100 calls @ 28us

[14:14:51] ======== Monitor (0): HistUpdater ========
[14:14:51] BuildHistogram: 0.014938s, 781 calls @ 14938us

[14:14:51] EvaluateSplits: 0.013255s, 1181 calls @ 13255us

[14:14:51] InitData: 0.003818s, 400 calls @ 3818us

[14:14:51] InitRoot: 0.011854s, 400 calls @ 11854us

[14:14:51] LeafPartition: 0.003071s, 400 calls @ 3071us

[14:14:51] UpdatePosition: 0.009947s, 1150 calls @ 9947us

[14:14:51] UpdateTree: 0.055726s, 400 calls @ 55726us

[14:14:51] ======== Monitor (0):  ========
[14:14:51] BuildHist: 0.013714s, 1181 calls @ 13714us

[14:14:51] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:14:51] ======== Monitor (0): HostSketchContainer ========
[14:14:51] AllReduce: 0.000334s, 1 calls @ 334us

[14:14:51] MakeCuts: 0.000378s, 1 calls @ 378us

[14:14:51] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:51] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:14:52] ======== Monitor (0): GBTree ========
[14:14:52] BoostNewTrees: 0.061318s, 100 calls @ 61318us

[14:14:52] CommitModel: 2.7e-05s, 100 calls @ 27us

[14:14:52] ======== Monitor (0): HistUpdater ========
[14:14:52] BuildHistogram: 0.01494s, 780 calls @ 14940us

[14:14:52] EvaluateSplits: 0.013056s, 1180 calls @ 13056us

[14:14:52] InitData: 0.003764s, 400 calls @ 3764us

[14:14:52] InitRoot: 0.01191s, 400 calls @ 11910us

[14:14:52] LeafPartition: 0.003081s, 400 calls @ 3081us

[14:14:52] UpdatePosition: 0.009674s, 1150 calls @ 9674us

[14:14:52] UpdateTree: 0.05532s, 400 calls @ 55320us

[14:14:52] ======== Monitor (0):  ========
[14:14:52] BuildHist: 0.014047s, 1180 calls @ 14047us

[14:14:52] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:14:52] ======== Monitor (0): HostSketchContainer ========
[14:14:52] AllReduce: 0.00034s, 1 calls @ 340us

[14:14:52] MakeCuts: 0.000384s, 1 calls @ 384us

[14:14:52] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:52] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:14:52] ======== Monitor (0): GBTree ========
[14:14:52] BoostNewTrees: 0.061728s, 100 calls @ 61728us

[14:14:52] CommitModel: 2.8e-05s, 100 calls @ 28us

[14:14:52] ======== Monitor (0): HistUpdater ========
[14:14:52] BuildHistogram: 0.014985s, 778 calls @ 14985us

[14:14:52] EvaluateSplits: 0.0132s, 1178 calls @ 13200us

[14:14:52] InitData: 0.003739s, 400 calls @ 3739us

[14:14:52] InitRoot: 0.011816s, 400 calls @ 11816us

[14:14:52] LeafPartition: 0.003102s, 400 calls @ 3102us

[14:14:52] UpdatePosition: 0.009887s, 1141 calls @ 9887us

[14:14:52] UpdateTree: 0.05557s, 400 calls @ 55570us

[14:14:52] ======== Monitor (0):  ========
[14:14:52] BuildHist: 0.013825s, 1178 calls @ 13825us

[14:14:52] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:14:53] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:53] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:54] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:54] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:54] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:55] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:55] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:56] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:56] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:57] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:14:58] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:14:58] ======== Monitor (0): GBLinear ========
[14:14:58] DoBoost: 0.133043s, 600 calls @ 133043us

[14:14:58] PredictBatch: 0.018313s, 600 calls @ 18313us

[14:14:58] PredictBatchInternal: 0.018148s, 600 calls @ 18148us

[14:14:58] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:14:58] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:14:58] ======== Monitor (0): GBLinear ========
[14:14:58] DoBoost: 0.129431s, 600 calls @ 129431us

[14:14:58] PredictBatch: 0.018288s, 600 calls @ 18288us

[14:14:58] PredictBatchInternal: 0.01813s, 600 calls @ 18130us

[14:14:58] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:14:58] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:14:58] ======== Monitor (0): GBLinear ========
[14:14:58] DoBoost: 0.129901s, 600 calls @ 129901us

[14:14:58] PredictBatch: 0.017891s, 600 calls @ 17891us

[14:14:58] PredictBatchInternal: 0.017734s, 600 calls @ 17734us

[14:14:58] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:14:58] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:14:59] ======== Monitor (0): GBLinear ========
[14:14:59] DoBoost: 0.153071s, 600 calls @ 153071us

[14:14:59] PredictBatch: 0.018283s, 600 calls @ 18283us

[14:14:59] PredictBatchInternal: 0.018124s, 600 calls @ 18124us

[14:14:59] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:14:59] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:14:59] ======== Monitor (0): GBLinear ========
[14:14:59] DoBoost: 0.157717s, 600 calls @ 157717us

[14:14:59] PredictBatch: 0.017393s, 600 calls @ 17393us

[14:14:59] PredictBatchInternal: 0.017226s, 600 calls @ 17226us

[14:14:59] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:03] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:03] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:03] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:03] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:03] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:03] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:03] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:03] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:03] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:03] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:09] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:09] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:10] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:10] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:10] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:11] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:11] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:11] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:11] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:11] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:11] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:11] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:11] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:12] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:12] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:12] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:12] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:12] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:12] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:12] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:12] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:12] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:12] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:12] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:12] INFO: /__w/xgboost/xgboost/src/gbm/gblinear.cc:80: Using the updater:shotgun
[14:15:12] ======== Monitor (0): HostSketchContainer ========
[14:15:12] AllReduce: 0.000362s, 1 calls @ 362us

[14:15:12] MakeCuts: 0.000407s, 1 calls @ 407us

[14:15:12] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:12] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:15:12] ======== Monitor (0): GBTree ========
[14:15:12] BoostNewTrees: 0.101491s, 100 calls @ 101491us

[14:15:12] CommitModel: 3e-05s, 100 calls @ 30us

[14:15:12] ======== Monitor (0): HistUpdater ========
[14:15:12] BuildHistogram: 0.032792s, 1467 calls @ 32792us

[14:15:12] EvaluateSplits: 0.024326s, 1867 calls @ 24326us

[14:15:12] InitData: 0.004383s, 400 calls @ 4383us

[14:15:12] InitRoot: 0.015613s, 400 calls @ 15613us

[14:15:12] LeafPartition: 0.003316s, 400 calls @ 3316us

[14:15:12] UpdatePosition: 0.016105s, 1700 calls @ 16105us

[14:15:12] UpdateTree: 0.096806s, 400 calls @ 96806us

[14:15:12] ======== Monitor (0):  ========
[14:15:12] BuildHist: 0.02487s, 1867 calls @ 24870us

[14:15:12] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:15:12] ======== Monitor (0): HostSketchContainer ========
[14:15:12] AllReduce: 0.000351s, 1 calls @ 351us

[14:15:12] MakeCuts: 0.000422s, 1 calls @ 422us

[14:15:12] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:12] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:15:12] ======== Monitor (0): GBTree ========
[14:15:12] BoostNewTrees: 0.101978s, 100 calls @ 101978us

[14:15:12] CommitModel: 3e-05s, 100 calls @ 30us

[14:15:12] ======== Monitor (0): HistUpdater ========
[14:15:12] BuildHistogram: 0.033734s, 1425 calls @ 33734us

[14:15:12] EvaluateSplits: 0.024272s, 1825 calls @ 24272us

[14:15:12] InitData: 0.004354s, 400 calls @ 4354us

[14:15:12] InitRoot: 0.015723s, 400 calls @ 15723us

[14:15:12] LeafPartition: 0.003365s, 400 calls @ 3365us

[14:15:12] UpdatePosition: 0.015621s, 1624 calls @ 15621us

[14:15:12] UpdateTree: 0.097262s, 400 calls @ 97262us

[14:15:12] ======== Monitor (0):  ========
[14:15:12] BuildHist: 0.02597s, 1825 calls @ 25970us

[14:15:12] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:15:12] ======== Monitor (0): HostSketchContainer ========
[14:15:12] AllReduce: 0.000373s, 1 calls @ 373us

[14:15:12] MakeCuts: 0.000419s, 1 calls @ 419us

[14:15:12] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:12] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:15:12] ======== Monitor (0): GBTree ========
[14:15:12] BoostNewTrees: 0.101847s, 100 calls @ 101847us

[14:15:12] CommitModel: 3.1e-05s, 100 calls @ 31us

[14:15:12] ======== Monitor (0): HistUpdater ========
[14:15:12] BuildHistogram: 0.032749s, 1428 calls @ 32749us

[14:15:12] EvaluateSplits: 0.024268s, 1828 calls @ 24268us

[14:15:12] InitData: 0.004436s, 400 calls @ 4436us

[14:15:12] InitRoot: 0.015594s, 400 calls @ 15594us

[14:15:12] LeafPartition: 0.003301s, 400 calls @ 3301us

[14:15:12] UpdatePosition: 0.015809s, 1661 calls @ 15809us

[14:15:12] UpdateTree: 0.096304s, 400 calls @ 96304us

[14:15:12] ======== Monitor (0):  ========
[14:15:12] BuildHist: 0.024823s, 1828 calls @ 24823us

[14:15:12] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:15:12] ======== Monitor (0): HostSketchContainer ========
[14:15:12] AllReduce: 0.000354s, 1 calls @ 354us

[14:15:12] MakeCuts: 0.000402s, 1 calls @ 402us

[14:15:12] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:12] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:15:12] ======== Monitor (0): GBTree ========
[14:15:12] BoostNewTrees: 0.101457s, 100 calls @ 101457us

[14:15:12] CommitModel: 2.8e-05s, 100 calls @ 28us

[14:15:12] ======== Monitor (0): HistUpdater ========
[14:15:12] BuildHistogram: 0.033329s, 1479 calls @ 33329us

[14:15:12] EvaluateSplits: 0.024464s, 1879 calls @ 24464us

[14:15:12] InitData: 0.004338s, 400 calls @ 4338us

[14:15:12] InitRoot: 0.015421s, 400 calls @ 15421us

[14:15:12] LeafPartition: 0.00333s, 400 calls @ 3330us

[14:15:12] UpdatePosition: 0.015727s, 1686 calls @ 15727us

[14:15:12] UpdateTree: 0.09683s, 400 calls @ 96830us

[14:15:12] ======== Monitor (0):  ========
[14:15:12] BuildHist: 0.024875s, 1879 calls @ 24875us

[14:15:12] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:15:12] ======== Monitor (0): HostSketchContainer ========
[14:15:12] AllReduce: 0.00035s, 1 calls @ 350us

[14:15:12] MakeCuts: 0.000397s, 1 calls @ 397us

[14:15:12] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).
[14:15:12] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:15:12] ======== Monitor (0): GBTree ========
[14:15:12] BoostNewTrees: 0.1022s, 100 calls @ 102200us

[14:15:12] CommitModel: 2.9e-05s, 100 calls @ 29us

[14:15:12] ======== Monitor (0): HistUpdater ========
[14:15:12] BuildHistogram: 0.033357s, 1441 calls @ 33357us

[14:15:12] EvaluateSplits: 0.024547s, 1841 calls @ 24547us

[14:15:12] InitData: 0.004304s, 400 calls @ 4304us

[14:15:12] InitRoot: 0.015724s, 400 calls @ 15724us

[14:15:12] LeafPartition: 0.003386s, 400 calls @ 3386us

[14:15:12] UpdatePosition: 0.015837s, 1646 calls @ 15837us

[14:15:12] UpdateTree: 0.097504s, 400 calls @ 97504us

[14:15:12] ======== Monitor (0):  ========
[14:15:12] BuildHist: 0.025406s, 1841 calls @ 25406us

[14:15:13] DEBUG: /__w/xgboost/xgboost/src/gbm/gbtree.cc:127: Using tree method: 0
[14:15:16] ======== Monitor (0): HostSketchContainer ========
[14:15:16] AllReduce: 0.000329s, 1 calls @ 329us

[14:15:16] MakeCuts: 0.000379s, 1 calls @ 379us

[14:15:16] INFO: /__w/xgboost/xgboost/src/data/iterative_dmatrix.cc:56: Finished constructing the `IterativeDMatrix`: (1280, 20, 25600).

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('scalar', StandardScaler()),
                                             ('xg',
                                              XGBClassifier(base_score=None,
                                                            booster=None,
                                                            callbacks=None,
                                                            colsample_bylevel=None,
                                                            colsample_bynode=None,
                                                            colsample_bytree=None,
                                                            device=None,
                                                            early_stopping_rounds=None,
                                                            enable_categorical=True,
                                                            eval_metric=None,
                                                            feature_types=None,
                                                            feature_weights=None,
                                                            gamma=None,
                                                            grow_polic...
                                        'xg__booster': ['gbtree', 'gblinear',
                                                        'dart'],
                                        'xg__colsample_bytree': [0.5, 0.7, 1.0],
                                        'xg__eta': [0.01, 0.5, 0.1],
                                        'xg__lambda': [0, 1, 2, 3, 4, 5, 6, 7,
                                                       8, 9, 10],
                                        'xg__max_depth': [3, 5, 7, 10, 15],
                                        'xg__min_child_weight': [1, 2, 5, 10,
                                                                 20],
                                        'xg__n_estimators': [50, 100, 200, 300,
                                                             400, 600, 800,
                                                             1200],
                                        'xg__subsample': [0.5, 0.7, 1.0],
                                        'xg__verbosity': [0, 1, 2, 3]},
                   random_state=42, scoring='accuracy', verbose=1)

In [76]:
print("Best Hyperparameters:")
print(xg_selector.best_params_)

print("Best CV Score:")
print(xg_selector.best_score_)

xg_pipeline = xg_selector.best_estimator_

Best Hyperparameters:
{'xg__verbosity': 2, 'xg__subsample': 1.0, 'xg__n_estimators': 200, 'xg__min_child_weight': 10, 'xg__max_depth': 15, 'xg__lambda': 10, 'xg__eta': 0.1, 'xg__colsample_bytree': 1.0, 'xg__booster': 'dart', 'xg__alpha': 2}
Best CV Score:
0.903125

In [77]:
xg_pred = xg_pipeline.predict(ada_X_test)
accuracy = accuracy_score(ada_y_test, xg_pred)
print(f"Test Accuracy: {accuracy}")

Test Accuracy: 0.9225

# 📌 Practice Summary & Learning Outcomes

In this practice notebook, I worked on the **Mobile Price Classification** dataset and explored several techniques used in real-world machine learning workflows.

The notebook covered:

* **Train/Test Split** for creating separate training and testing data.
* **Scikit-learn Pipelines** to combine preprocessing and model training into a single workflow.
* **Cross-Validation** to evaluate model stability across different data splits.
* **GridSearchCV** for exhaustively searching through different hyperparameter combinations.
* **RandomizedSearchCV** for efficiently exploring a selected number of hyperparameter combinations.
* **Random Forest** as an ensemble learning method based on multiple decision trees.
* **Stacking** to combine predictions from multiple different models through a final estimator.
* **Boosting algorithms** to understand how models can be built sequentially to improve prediction performance.

### 🧠 What I Learned

Although several of these techniques did **not produce a significant improvement in performance on this particular dataset**, that does not make them unnecessary.

Different datasets have different characteristics, and a technique that provides only a small improvement on one dataset can be highly useful on another. Therefore, it was important to understand **how these techniques work, when they should be used, how to implement them, and how to evaluate whether they actually improve a model**.

This practice was mainly focused on building a strong understanding of the **machine learning workflow**, rather than simply trying to achieve the highest possible score on one dataset.

### 🚀 What's Next?

This notebook uses **Scikit-learn implementations** to understand ensemble learning from a practical perspective.

After completing the practical implementations, I plan to **implement the core ensemble learning algorithms from scratch**, including **Random Forest, Stacking, and Boosting algorithms**, to gain a deeper understanding of their internal mechanisms and mathematical foundations.

The goal is to understand not only **how to use machine learning algorithms**, but also **how they work internally**.